arch: arm64

language: c

compiler: gcc

sudo: required

services:
  - docker
  
  
before_install:
- docker build -t  johngong/qbittorrent:qee_4.1.8.2_arm64v8     ./qBittorrent  -f   ./qBittorrent/Dockerfile.aarch64

script:
- echo "$DOCKER_PASSWORD" | docker login  --username  "$DOCKER_USERNAME" --password-stdin
- docker push  johngong/qbittorrent:qee_4.1.8.2_arm64v8


