name: Build anki-sync-server-Tags Image

on:
  push:
    paths:
    - '.github/workflows/anki-sync-server-Tags-buildx.yml'

env:
  ANKI-SYNC-SERVER_VER: 2.1.0

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKERHUB_REPOSITORY: johngong/anki-sync-server
         README_FILEPATH: ./anki-sync-server/README.md
