name: Build anki-sync-server-Tags Image

on:
  push:
    paths:
    - '.github/workflows/anki-sync-server-Tags-buildx.yml'

env:
  ANKI-SYNC-SERVER_VER: 2.1.0

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --tag johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }} \
          --file ./anki-sync-server/Dockerfile ./anki-sync-server

      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform linux/amd64 \
          --output "type=image,push=true" \
          --tag johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_amd64 \
          --file ./anki-sync-server/Dockerfile ./anki-sync-server

      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform linux/arm64 \
          --output "type=image,push=true" \
          --tag johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_arm64v8 \
          --file ./anki-sync-server/Dockerfile ./anki-sync-server

      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform linux/arm/v7 \
          --output "type=image,push=true" \
          --tag johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_arm32v7 \
          --file ./anki-sync-server/Dockerfile ./anki-sync-server

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         DOCKERHUB_REPOSITORY: johngong/anki-sync-server
         README_FILEPATH: ./anki-sync-server/README.md
