name: Build baidunetdisk-latest Image

on:
  push:
    paths:
    - 'baidunetdisk/Dockerfile'
    - 'baidunetdisk/root/**'
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./baidunetdisk
          file:  ./baidunetdisk/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/baidunetdisk:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKERHUB_REPOSITORY: johngong/baidunetdisk
         README_FILEPATH: ./baidunetdisk/README.md
