name: Build tt-rss-plugins-Tags Image

on:
  push:
    paths:
    - '.github/workflows/tt-rss-plugins-Tags-buildx.yml'
  workflow_dispatch:

env:
  TTRSS_VER: 20.11-81c52b4b1

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tt-rss-plugins
          file: ./tt-rss-plugins/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/tt-rss:plugins-${{ env.TTRSS_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tt-rss-plugins
          file: ./tt-rss-plugins/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/tt-rss:plugins-${{ env.TTRSS_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tt-rss-plugins
          file: ./tt-rss-plugins/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/tt-rss:plugins-${{ env.TTRSS_VER }}_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tt-rss-plugins
          file: ./tt-rss-plugins/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/tt-rss:plugins-${{ env.TTRSS_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKERHUB_REPOSITORY: johngong/tt-rss
         README_FILEPATH: ./tt-rss-plugins/README.md
